Assignment 3

COMP 5600/6600

Due: 10/25/2023 11:59 pm

[Question 1]

[15 points]

Design a convolutional neural network in Keras of at least 10 convolutional layers. Use the MNIST
dataset for evaluation. You must try three designs as detailed below and provide your
observations on the performance of each:
1. A regular CNN where the number of filters in each layer increases as the depth of the
network grows i.e., the Lth layer will have more filters than the (L-1)th layer.
2. An inverted CNN where the number of filters in each layer decreases as the depth of the
network grows i.e., the Lth layer will have less filters than the (L-1)th layer.
3. An hour-glass shaped CNN where the number of filters will increase till the Lth layer and
reduce afterwards.
Your goal is to design these networks and optimize them to their best performance by choosing
the right hyperparameters for each network, such as the learning rate, batch size and the choice
of optimizer (‘SGD’, ‘adam’, ‘RMSProp’). You must provide a detailed report of what values you
tried for each hyperparameters, your observations on why the network performed well (or not)
and the final accuracy for each network on the MNIST dataset.
You can refer to the Keras documentation for more details

Report:

Whening testing different hyperparameters I started by testing different learing rate. I tried four different learning rates 0.1, 0.01, 0.001, 0.0001
the first three values seemed to not give the model enough time to learn from the training data resulting in very low accuracy scores and very high loss scores I ended up using 0.0001 because it gave the model enough time to learn from the training data to result in a high accuracy and low lose scores when used on the test data. Next I tried different batch sizes smaller batch sizes such as 32 made the trianing run slower and resulted in a larger disparity between the trianing data accuracy. On the other side high batch sizes such as 128 and 512 resulted in the training of the model running faster but overfit the data resulting in a very low accuracy when tested on the test data. When testing different opimizers they all had similar performaces but 'adam' would always test with the highest accuracy.Because of the previously mentioned testing I settled on using a learing rate of 0.0001 a batch size of 64 and 'Adam' as my choice of optimizer this resulted in my test accuracy ,for my first type of CNN architecture where layer l has more filters then layer l-1, being about 0.9859 then for my CNN with the architecture of layer l having fewer layer then layer l-1 having a test accuracy of 0.9768 and then finaly for my CNN that should be hour glass shaped resulted in a test accuracy of 0.9839.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers, models
from keras.datasets import mnist

# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train, x_test = np.expand_dims(x_train, axis=-1), np.expand_dims(x_test, axis=-1)

model = models.Sequential()

num_filters = 8

#adding first layer to the model
model.add(layers.Conv2D(num_filters, (3,3), activation='relu', padding='same', input_shape=(28,28,1)))

#adding next nine layers to the model and doubling the number of filters for each layer
for i in range (9):
  num_filters *= 2
  model.add(layers.Conv2D(num_filters, (3,3), activation='relu', padding='same'))

#flattening model to make a one diminsional array
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

#training model
model.fit(x_train, y_train, epochs=1, batch_size=64, validation_data=(x_test,y_test))

#evaluating model
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Loss: {0} - Test Acc: {1}".format(test_loss, test_acc))

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers, models
from keras.datasets import mnist

# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train, x_test = np.expand_dims(x_train, axis=-1), np.expand_dims(x_test, axis=-1)

model = models.Sequential()

num_filters = 4096

#adding first layer to the model
model.add(layers.Conv2D(num_filters, (3,3), activation='relu', padding='same', input_shape=(28,28,1)))

#adding next nine layers to the model and doubling the number of filters for each layer
for i in range (9):
  num_filters = num_filters/2
  model.add(layers.Conv2D(num_filters, (3,3), activation='relu', padding='same'))

#flattening model to make a one diminsional array
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

#training model
model.fit(x_train, y_train, epochs=1, batch_size=64, validation_data=(x_test,y_test))

#evaluating model
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Loss: {0} - Test Acc: {1}".format(test_loss, test_acc))

313/313 [==============================] - 126s 404ms/step - loss: 0.0751 - accuracy: 0.9768
Test Loss: 0.07507205754518509 - Test Acc: 0.9768000245094299


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers, models
from keras.datasets import mnist

# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train, x_test = np.expand_dims(x_train, axis=-1), np.expand_dims(x_test, axis=-1)

model = models.Sequential()

num_filters = 32

#adding first layer to the model
model.add(layers.Conv2D(num_filters, (3,3), activation='relu', padding='same', input_shape=(28,28,1)))

#adding next nine layers to the model and doubling the number of filters for each layer
for i in range (4):
  num_filters *= 2
  model.add(layers.Conv2D(num_filters, (3,3), activation='relu', padding='same'))

for i in range (5):
  num_filters /= 2
  model.add(layers.Conv2D(num_filters, (3,3), activation='relu', padding='same'))

#flattening model to make a one diminsional array
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

#training model
model.fit(x_train, y_train, epochs=1, batch_size=64, validation_data=(x_test,y_test))

#evaluating model
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Loss: {0} - Test Acc: {1}".format(test_loss, test_acc))

313/313 [==============================] - 6s 18ms/step - loss: 0.0534 - accuracy: 0.9839
Test Loss: 0.053366754204034805 - Test Acc: 0.9839000105857849


[Question 2]

 [25 points]

Implement the LeNet Convolutional Neural Network using Keras. It is a seven-layer network with
three convolutional layers, two max-pooling layers and 2 dense layers. The structure is shown
below:

Layer 1: convolution layer with 6 convolution kernels of 5x5 with stride 1

Layer 2: max-pooling layer with 2x2 kernels with stride 2

Layer 3: convolution layer with 16 convolution kernels of 5x5 with stride 1

Layer 4: max-pooling layer with 2x2 kernels with stride 2

Layer 5: convolution layer with 120 convolution kernels of 5x5

Layer 6: dense layer with 84 neurons

Layer 7: output layer

Use the ‘Adam’ optimizer to train your network on the CIFAR-10 dataset for a fixed set of 25
epochs. You can use the built-in functions to load the data. Each image is 32x32x3 matrix and you
will have 60,000 images for training and 10,000 for test. There are 10 classes in the dataset each
representing an object in the image.
Perform the following analysis and answer each question briefly (3-5 sentences). Use plots and
figures as necessary.
1. What is the effect of learning rate on the training process? Which performed best?
2. What is the effect of batch size on the training process? Which performed best?
3. Try different hyperparameters to obtain the best accuracy on the test set. What is your
best performance and what were the hyperparameters?
4. Implement an equivalent feed forward network for the same task with each hidden layer
containing the same number of neurons as the number of filters in each convolution layer.
Use the ‘Adam’ optimizer to train your network on the CIFAR-10 dataset for a fixed set of
25 epochs. Compare its performance with your LeNet implementation based on the
following questions:
a. What is its performance?
b. How many parameters are there in this network compared to the LeNet
implementation? Are they worth it?

Report:
1. the effect of the learning rate is how fast the model learns from the data during training. During my expirementation I tried learing rates of 0.1 and 0.01 which seemed to underfit the data leading to the model making very inaccurate predictions. I also tried 0.0001 which resulted in the model overfitting the data during trianing and also leading to a low accuracy in testing. I ended up using 0.001 which resulted in the best accuracy and seemed to fit the data well.
2. When testing different batch sizes I noticed that the small batch sizes(such as 32 and 64) slowed down the training process but were able to capture features from the data better shown in higher accuracy scores where as having to large of a batch size(such as 128, 512, and 1024) increased the speed at which the training completed but lead to the model working well for the training data but preforming poorly on the actual test data.Because of this I settled on the batch size of 32.
3. I tried different different hyperparameters but ended up using a learning rate of 0.001 and a batch size of 32 with the specified acritecture above and the best accuracy from training I recieved was 0.7594 with a loss of 0.6752 and during testing I recieved an accuracy of 0.6030 with a loss of 1.3338.
4.
  1) When implementing the feed forward network the performance was signifagantly worse than the lenet network, with the accuracy for the lenet being 0.6030 compared to the accuracy of the feed forward network being 0.2088
  
  2) because of the conflusion of the previous question and the fact that the lenet nework as more trainable parameters than the feed forward netowrk i would say that the extra parameters are worth it since they resulted in the higher accuracy and lower loss of data

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers, models
from keras.datasets import cifar10

# Load and preprocess the cifar10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = models.Sequential()

#adding first layer to the model
model.add(layers.Conv2D(6, (5, 5), activation='relu', padding='valid', strides=(1, 1), input_shape=(32, 32, 3)))

#second layer
model.add(layers.MaxPooling2D((2, 2), strides=(2, 2)))

#third layer
model.add(layers.Conv2D(16, (5, 5), activation='relu', padding='valid', strides=(1, 1)))

#fourth layer
model.add(layers.MaxPooling2D((2, 2), strides=(2, 2)))

#fifth layer
model.add(layers.Conv2D(120, (5, 5), activation='relu', padding='valid'))

#flattening model to make a one diminsional array
model.add(layers.Flatten())

#sixth layer
model.add(layers.Dense(84, activation='relu'))

#seventh layer
model.add(layers.Dense(10, activation='softmax'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

#training model
model.fit(x_train, y_train, epochs=25, batch_size=32, validation_data=(x_test,y_test))

#evaluating model
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Loss: {0} - Test Acc: {1}".format(test_loss, test_acc))

170498071/170498071 [==============================] - 4s 0us/step
Epoch 1/25
1563/1563 [==============================] - 12s 5ms/step - loss: 1.6083 - accuracy: 0.4152 - val_loss: 1.3949 - val_accuracy: 0.4888
Epoch 2/25
1563/1563 [==============================] - 8s 5ms/step - loss: 1.3356 - accuracy: 0.5214 - val_loss: 1.3898 - val_accuracy: 0.5052
Epoch 3/25
1563/1563 [==============================] - 7s 4ms/step - loss: 1.2217 - accuracy: 0.5630 - val_loss: 1.1993 - val_accuracy: 0.5734
Epoch 4/25
1563/1563 [==============================] - 8s 5ms/step - loss: 1.1472 - accuracy: 0.5915 - val_loss: 1.1876 - val_accuracy: 0.5809
Epoch 5/25
1563/1563 [==============================] - 8s 5ms/step - loss: 1.0856 - accuracy: 0.6156 - val_loss: 1.2010 - val_accuracy: 0.5774
Epoch 6/25
1563/1563 [==============================] - 7s 5ms/step - loss: 1.0391 - accuracy: 0.6325 - val_loss: 1.1329 - val_accuracy: 0.6009
Epoch 7/25
1563/1563 [==============================] - 8s 5ms/step 

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers, models
from keras.datasets import cifar10

# Load and preprocess the cifar10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = models.Sequential()

#feed forward NN implementation
#flattening model to make a one diminsional array
model.add(layers.Flatten(input_shape=(32,32,3)))

model.add(layers.Dense(6, activation='relu'))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(120, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))


optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

#training model
model.fit(x_train, y_train, epochs=25, batch_size=32, validation_data=(x_test,y_test))

#evaluating model
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Loss: {0} - Test Acc: {1}".format(test_loss, test_acc))

Epoch 1/25
1563/1563 [==============================] - 8s 4ms/step - loss: 2.0874 - accuracy: 0.1819 - val_loss: 2.0410 - val_accuracy: 0.2036
Epoch 2/25
1563/1563 [==============================] - 6s 4ms/step - loss: 2.0468 - accuracy: 0.1922 - val_loss: 2.0261 - val_accuracy: 0.2002
Epoch 3/25
1563/1563 [==============================] - 7s 4ms/step - loss: 2.0385 - accuracy: 0.1978 - val_loss: 2.0272 - val_accuracy: 0.2060
Epoch 4/25
1563/1563 [==============================] - 8s 5ms/step - loss: 2.0329 - accuracy: 0.2007 - val_loss: 2.0235 - val_accuracy: 0.2026
Epoch 5/25
1563/1563 [==============================] - 6s 4ms/step - loss: 2.0337 - accuracy: 0.2028 - val_loss: 2.0433 - val_accuracy: 0.1943
Epoch 6/25
1563/1563 [==============================] - 6s 4ms/step - loss: 2.0320 - accuracy: 0.2013 - val_loss: 2.0378 - val_accuracy: 0.2033
Epoch 7/25
1563/1563 [==============================] - 7s 5ms/step - loss: 2.0302 - accuracy: 0.2051 - val_loss: 2.0163 - val_accuracy:

[Question 3]

 [10 points]

Consider the below matrices as input (X) and convolutional kernel f. Consider that the depth of
the input is 1.



Compute the following:
1. What are the dimensions of the input and the kernel (or filter)? How many parameters
are there in the kernel f? [2 points]
2. What is the output activation map when you apply the convolutional operation using the
filter f on the input X without padding? [4 points]
3. What is the output when you apply a max-pooling operation on the output from the
previous question? [4 points]

Note: For parts 2 and 3 in question 3, please provide the actual output. You can work this one
out by hand or write your own code to do it. Provide documentation of how you got the outputs.


In [ ]:
import numpy as np

input_matrix = np.array([[7, 5, 0, 0, 3, 2],
                         [6, 4, 5, 1, 4, 8],
                         [9, 0, 2, 2, 5, 4],
                         [6, 3, 4, 7, 9, 8],
                         [5, 7, 5, 6, 9, 0],
                         [7, 9, 0, 8, 2, 3]])

filter_matrix = np.array([[1, 0, -1],
                          [2, 0, -2],
                          [1, 0, -1]])

# Code for Question 1
input_height, input_width = input_matrix.shape
filter_height, filter_width = filter_matrix.shape
num_parameters = filter_height * filter_width
print("Question 1:")
print(f"Input Dimensions: ({input_height}, {input_width})")
print(f"Filter Dimensions: ({filter_height}, {filter_width})")
print(f"Number of Parameters in the Filter: {num_parameters}")

# Code for Question 2
output_matrix = np.zeros((input_height - filter_height + 1, input_width - filter_width + 1))
for i in range(input_height - filter_height + 1):
    for j in range(input_width - filter_width + 1):
        output_matrix[i, j] = np.sum(input_matrix[i:i+filter_height, j:j+filter_width] * filter_matrix)

print("Question 2:")
print("Output Matrix after Convolution:")
print(output_matrix)

# Code for Question 3
pooling_size = 2  # Pooling window size
output_height, output_width = output_matrix.shape
pooled_matrix = np.zeros((output_height // pooling_size, output_width // pooling_size))

for i in range(0, output_height, pooling_size):
    for j in range(0, output_width, pooling_size):
        pooled_matrix[i // pooling_size, j // pooling_size] = np.max(output_matrix[i:i+pooling_size, j:j+pooling_size])

print("Question 3:")
print("Output Matrix after Max-Pooling:")
print(pooled_matrix)



Question 1:
Input Dimensions: (6, 6)
Filter Dimensions: (3, 3)
Number of Parameters in the Filter: 9
Question 2:
Output Matrix after Convolution:
[[ 16.   9.  -4. -18.]
 [ 17.  -5. -10. -12.]
 [ 11.  -9. -17.   2.]
 [  9.  -1. -15.  16.]]
Question 3:
Output Matrix after Max-Pooling:
[[17. -4.]
 [11. 16.]]
